[package]
name = "module-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "*"
wasmer-wasi = "*"
wasmer-compiler-llvm = "*"
llvm-sys = "130"