[package]
name = "base64-helper"
version = "0.1.0"
edition = "2021"
authors = ["Maximilian Wolf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "*"